name: on the train
favicon: null
layout_spectrum: 0.6002824341412634
typography_spectrum: 0.17434806283563375
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.008722681552171707
  lightness: 0.2570382112171501
  saturation: 0.7902253121137619
  rhythmicContrast: 0.8013424724340439
purpose: []
